### ISSUE TITLE
1chipMSX cannot use the gopher browser

### ISSUE THREAD

**Issue by denjhang** [nihirash/moon-rabbit#1]
![无法使用地鼠浏览器](https://github.com/nihirash/moon-rabbit/assets/61811583/1235a111-3356-4175-ad00-56c84da39f81)
I have a clone of OCM with unapi, it works fine for networking apps like HUB, but when I open moonr, there is only wrong screen.

**Comment by nihirash** [comment]
Sorry, I have no access to any MSX machine now but.. 

Did you started it from CLI or some file manager(if from file manager - try start from CLI)?

**Comment by denjhang** [comment]
It is indeed a path problem, currently I use:
cd moonr
moonr
solved the problem. When using sofarun, the screen will be blurred.
